### ISSUE TITLE
Setup Travis CI integration

### ISSUE THREAD

**Issue by alldigital** [alldigital/CriminalIntent#1]
Setup Travis CI integration for this project as an example

**Comment by alldigital** [comment]
This snippet does the job:

```
deploy:
  provider: releases
  api_key:
    secure: ee0vQITijl4ENKWGymgMOr1BUwKlQTWmt9I1dTquJ0vMgNHDqof/MSvevQxdoCPpg49MVLV1splXUkhK8jw212RMn/F3oLFi6v4aGBbbRLZrgd8jQRcWA9CkIsN6rv62sJAPAAHvkXbIxOMgxsNf10fSzOe0tXRKgDQn0rd0up+UVXmkfrSn6Mj+2D5hLIevn+TazfyfwTTBvUxZydkBwz+8G2uOCSIZbk48JZPLPN66bsiTQgNx9q+kN9qDe+SYNMnsgoD3acwNelViOddY+Cp/GsmzauIX1sch/fL2Ey1BmaPOIIGcTYqBys1f8VKiS1Xaku4oV0D8GjqwnJNzY9nGvU0JvSsVU2ay0n9hXSqHYcdl/RTbXM16HL03hZxaKAYq3bAU+11GFr6vVqKYainLtqqTxDdS043vubvfsPUdsRrWDZRlc5oCvtXCdIet/4xwBfR9Sx2gOzB+v2sSMgZiyvdzJPBR42WAbXU23Ev2ZbRxdEKLS1dgtN6Semf3hqVZFCXgHoPcStBykMH2j9/KIvP+AjAaSAlmTtAXT0GvRyR4OYIihgwcKHTnzQYGJZN7q+9cqK+291aP9j03SDwZsymItnyDGLTkWDB5Hyx7+4wmx+OgzwpeTjDdeQOYyOwe88gXUnOkdtnqgrBFE6UiY2ixEopB1Bcur5sg6G0=
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  overwrite:    true
  on:
    repo: alldigital/CriminalIntent
    tags: true

```
